name:  Despliegue y Build de Docker

on:
  push:
    branches:
      - "main"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v2

    - name: Build de la imagen Docker
      run: docker build -t gobd .

    - name: Iniciar contenedor Docker
      run: docker run -d -p 8080:80 gobd