apiVersion: v1
kind: Service
metadata:
  name: gobd-service  # Cambia el nombre aquí
spec:
  selector:
    app: gobd  # Asegúrate de que coincida con el valor del label 'app' en el Deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

